/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/Card.vue')['default']
    Container: typeof import('./src/components/Container.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    IEpAddLocation: typeof import('~icons/ep/add-location')['default']
    IEpAim: typeof import('~icons/ep/aim')['default']
    IEpCircleCheckFilled: typeof import('~icons/ep/circle-check-filled')['default']
    IEpCircumAirportSign1: typeof import('~icons/ep/circum-airport-sign1')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Swiper: typeof import('./src/components/Swiper.vue')['default']
  }
}
